package services;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import mprKursPrawaJazdy.*;

public class OsrodkiDBManager {

	private Connection conn;

	private Statement stmt;

	private PreparedStatement addOsrodkiStmt;
	private PreparedStatement getOsrodkiStmt;


	public OsrodkiDBManager()
	{
		try {

			conn= DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

			stmt=conn.createStatement();
			boolean osrodkiTableExists=false;

			ResultSet rs= conn.getMetaData().getTables(null, null, null, null);

			while(rs.next())
			{
				if("Osrodki".equalsIgnoreCase(rs.getString("TABLE_NAME")))
					{
						osrodkiTableExists=true;
						break;
					}
			}


			if(!osrodkiTableExists)
			{
				stmt.executeUpdate("" +
					"CREATE TABLE osrodki(" +
					"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
					"nazwa varchar(20)," +
					"" +
					")");
			}

			addOsrodkiStmt=conn.prepareStatement("" +
					"INSERT INTO osrodki (nazwa) VALUES (?)" +
					"");

			getOsrodkiStmt=conn.prepareStatement("" +
					"SELECT * FROM osrodki" +
					"");



		} catch (SQLException e) {

			e.printStackTrace();
		}
	}

	public void addOsrodki(Osrodki p)
	{
		try {
			addOsrodkiStmt.setString(1, p.getNazwa());

			addOsrodkiStmt.executeUpdate();

		} catch (SQLException e) {

			e.printStackTrace();
		}

	}

	public List<Osrodki> getAllOsrodki()
	{
		List<Osrodki> osrodki=new ArrayList<Osrodki>();

		try {
			ResultSet rs= getOsrodkiStmt.executeQuery();

			while(rs.next())
			{
				osrodki.add(new Osrodki(rs.getString("nazwa")));
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		return osrodki;
	}


}

